In [18]:
import time

import numpy as np
import pandas as pd
import tiktoken
from google import genai
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

## Task 1

In [ ]:
client = genai.Client()

In [60]:
sentences = [
    "Artificial intelligence is changing modern technology.",  # Technology
    "Machine learning helps computers learn from data.",  # Technology
    "Neural networks are widely used in artificial intelligence.",  # Technology
    "New computer processors are becoming faster.",  # Technology
    "The football team won the championship.",  # sport
    "The coach trained the team for the tournament.",  # sport
    "The player scored three goals in the match.",  # sport
    "Fresh vegetables make a healthy salad.",  # Food
    "Pizza is a popular Italian food.",  # Food
    "The chef prepared a delicious pasta dish.",  # Food
]

embeddings = client.models.embed_content(
    model="gemini-embedding-001",
    contents=sentences,
    config={"output_dimensionality": 384},
)

In [61]:
embeddings = embeddings.embeddings

df = pd.DataFrame(
    cosine_similarity([e.values for e in embeddings]),
    index=sentences,
    columns=sentences,
)
print(df)

                                                    Artificial intelligence is changing modern technology.  \
Artificial intelligence is changing modern tech...                                           1.000000        
Machine learning helps computers learn from data.                                            0.660008        
Neural networks are widely used in artificial i...                                           0.718112        
New computer processors are becoming faster.                                                 0.654160        
The football team won the championship.                                                      0.522335        
The coach trained the team for the tournament.                                               0.539186        
The player scored three goals in the match.                                                  0.490884        
Fresh vegetables make a healthy salad.                                                       0.469241        
Pizza is a

## Task 2

In [15]:
model = SentenceTransformer("all-MiniLM-L6-v2")

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2082.26it/s]


In [ ]:
embeddings2 = model.encode(sentences)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6665.95it/s]


In [38]:
similarity_matrix = cosine_similarity(embeddings2)

# Print similarity matrix
np.set_printoptions(precision=2, suppress=True)
print(similarity_matrix)

[[ 1.    0.47  0.55  0.48  0.03  0.12 -0.08 -0.03  0.1   0.03]
 [ 0.47  1.    0.54  0.32  0.15  0.23  0.01  0.03  0.08  0.1 ]
 [ 0.55  0.54  1.    0.28  0.06  0.16 -0.03 -0.01  0.11  0.07]
 [ 0.48  0.32  0.28  1.   -0.04  0.02 -0.09  0.09  0.13  0.05]
 [ 0.03  0.15  0.06 -0.04  1.    0.33  0.25 -0.02  0.03  0.04]
 [ 0.12  0.23  0.16  0.02  0.33  1.    0.3  -0.02  0.02  0.19]
 [-0.08  0.01 -0.03 -0.09  0.25  0.3   1.    0.01  0.04  0.12]
 [-0.03  0.03 -0.01  0.09 -0.02 -0.02  0.01  1.    0.19  0.22]
 [ 0.1   0.08  0.11  0.13  0.03  0.02  0.04  0.19  1.    0.47]
 [ 0.03  0.1   0.07  0.05  0.04  0.19  0.12  0.22  0.47  1.  ]]


In [62]:
for i in range(len(sentences)):
    print(f"{sentences[i]} : {cosine_similarity([embeddings[i].values], [embeddings2[i]])}")

Artificial intelligence is changing modern technology. : [[0.01]]
Machine learning helps computers learn from data. : [[0.01]]
Neural networks are widely used in artificial intelligence. : [[0.02]]
New computer processors are becoming faster. : [[0.05]]
The football team won the championship. : [[-0.06]]
The coach trained the team for the tournament. : [[0.03]]
The player scored three goals in the match. : [[-0.03]]
Fresh vegetables make a healthy salad. : [[0.04]]
Pizza is a popular Italian food. : [[0.02]]
The chef prepared a delicious pasta dish. : [[-0.03]]


## Task 3

In [65]:
embeddings_fix_size = model.encode(sentences, chunk_size=768)
embeddings_fix_size2 = model.encode(sentences, chunk_size=1536)

In [64]:
similarity_matrix = cosine_similarity(embeddings_fix_size)

# Print similarity matrix
np.set_printoptions(precision=2, suppress=True)
print(similarity_matrix)

[[ 1.    0.47  0.55  0.48  0.03  0.12 -0.08 -0.03  0.1   0.03]
 [ 0.47  1.    0.54  0.32  0.15  0.23  0.01  0.03  0.08  0.1 ]
 [ 0.55  0.54  1.    0.28  0.06  0.16 -0.03 -0.01  0.11  0.07]
 [ 0.48  0.32  0.28  1.   -0.04  0.02 -0.09  0.09  0.13  0.05]
 [ 0.03  0.15  0.06 -0.04  1.    0.33  0.25 -0.02  0.03  0.04]
 [ 0.12  0.23  0.16  0.02  0.33  1.    0.3  -0.02  0.02  0.19]
 [-0.08  0.01 -0.03 -0.09  0.25  0.3   1.    0.01  0.04  0.12]
 [-0.03  0.03 -0.01  0.09 -0.02 -0.02  0.01  1.    0.19  0.22]
 [ 0.1   0.08  0.11  0.13  0.03  0.02  0.04  0.19  1.    0.47]
 [ 0.03  0.1   0.07  0.05  0.04  0.19  0.12  0.22  0.47  1.  ]]


In [66]:
similarity_matrix = cosine_similarity(embeddings_fix_size2)

# Print similarity matrix
np.set_printoptions(precision=2, suppress=True)
print(similarity_matrix)

[[ 1.    0.47  0.55  0.48  0.03  0.12 -0.08 -0.03  0.1   0.03]
 [ 0.47  1.    0.54  0.32  0.15  0.23  0.01  0.03  0.08  0.1 ]
 [ 0.55  0.54  1.    0.28  0.06  0.16 -0.03 -0.01  0.11  0.07]
 [ 0.48  0.32  0.28  1.   -0.04  0.02 -0.09  0.09  0.13  0.05]
 [ 0.03  0.15  0.06 -0.04  1.    0.33  0.25 -0.02  0.03  0.04]
 [ 0.12  0.23  0.16  0.02  0.33  1.    0.3  -0.02  0.02  0.19]
 [-0.08  0.01 -0.03 -0.09  0.25  0.3   1.    0.01  0.04  0.12]
 [-0.03  0.03 -0.01  0.09 -0.02 -0.02  0.01  1.    0.19  0.22]
 [ 0.1   0.08  0.11  0.13  0.03  0.02  0.04  0.19  1.    0.47]
 [ 0.03  0.1   0.07  0.05  0.04  0.19  0.12  0.22  0.47  1.  ]]


## task 4 - pipeline

In [12]:
documents = [
    "Artificial intelligence is changing modern technology.",  # Technology
    "Machine learning helps computers learn from data.",  # Technology
    "Neural networks are widely used in artificial intelligence.",  # Technology
    "New computer processors are becoming faster.",  # Technology
    "The football team won the championship.",  # sport
    "The coach trained the team for the tournament.",  # sport
    "The player scored three goals in the match.",  # sport
    "Fresh vegetables make a healthy salad.",  # Food
    "Pizza is a popular Italian food.",  # Food
    "The chef prepared a delicious pasta dish.",  # Food
]

In [ ]:
class RetriveDocument:
    def __init__(self):
        self.model = SentenceTransformer("all-MiniLM-L6-v2")
        self.tokenizer = tiktoken.get_encoding("cl100k_base")

    def build_search_index(self, documents: list[str]) -> list[tuple[str, np.ndarray]]:
        chunks = [chunk for doc in documents for chunk in self._chunk_text(doc)]
        embedding = self._build_embeddings(chunks)

        return list(zip(chunks, embedding))

    def semantic_search(self, query: str, index: list[tuple[str, np.ndarray]], top_k: int = 3):
        query_embedding = self._build_embeddings([query])
        scored = [
            (
                chunk,
                cosine_similarity(query_embedding, chunk_embedding.reshape(1, -1))[0][0],
            )
            for chunk, chunk_embedding in index
        ]

        scored.sort(key=lambda x: x[1], reverse=True)

        return scored[:top_k]

    def _chunk_text(self, text: str, chunk_size_tokens: int = 500, overlaps_token: int = 50):
        tokens = self.tokenizer.encode(text)
        chunks = []
        start = 0
        while start < len(tokens):
            end = min(start + chunk_size_tokens, len(tokens))
            chunks.append(self.tokenizer.decode(tokens[start:end]))
            start += chunk_size_tokens - overlaps_token
        return chunks

    def _build_embeddings(self, texts: list[str]) -> np.ndarray:
        return self.model.encode(texts)

In [77]:
retrive_document = RetriveDocument()

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 7251.71it/s]


In [ ]:
index = retrive_document.build_search_index(documents)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 8036.26it/s]


In [78]:
retrivals = retrive_document.semantic_search(query="Who is changing modern technology", index=index)

[('Artificial intelligence is changing modern technology.', np.float32(0.6880261)), ('Machine learning helps computers learn from data.', np.float32(0.17133568)), ('Neural networks are widely used in artificial intelligence.', np.float32(0.20511544)), ('New computer processors are becoming faster.', np.float32(0.409689)), ('The football team won the championship.', np.float32(-0.037943922)), ('The coach trained the team for the tournament.', np.float32(0.029821398)), ('The player scored three goals in the match.', np.float32(-0.09340739)), ('Fresh vegetables make a healthy salad.', np.float32(-0.008425577)), ('Pizza is a popular Italian food.', np.float32(0.03672751)), ('The chef prepared a delicious pasta dish.', np.float32(0.04152316))]


In [79]:
retrivals

[('Artificial intelligence is changing modern technology.',
  np.float32(0.6880261)),
 ('New computer processors are becoming faster.', np.float32(0.409689)),
 ('Neural networks are widely used in artificial intelligence.',
  np.float32(0.20511544))]

## task 6

In [ ]:
import numpy as np
from sentence_transformers import SentenceTransformer

e5 = SentenceTransformer("intfloat/e5-base-v2")
minilm = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

documents = [
    "Python is a programming language commonly used for data science and machine learning.",
    "The Eiffel Tower is a famous landmark located in Paris, France.",
    "Neural networks are machine learning models inspired by the human brain.",
    "The Pacific Ocean is the largest ocean on Earth.",
    "Pandas is a Python library used for data manipulation and analysis.",
    "Transformers are neural network architectures widely used in natural language processing.",
    "Mount Everest is the highest mountain above sea level.",
    "SQL is a language used to query and manipulate relational databases.",
]

queries = [
    "What Python library is useful for manipulating datasets?",
    "Which architecture is widely used for NLP?",
    "What is the highest mountain in the world?",
    "Which ocean is the biggest?",
]


# Ground-truth relevant document for each query
relevant = {
    0: 4,  # Pandas
    1: 5,  # Transformers
    2: 6,  # Everest
    3: 3,  # Pacific Ocean
}


def retrieve(model, queries, documents, asymmetric=False, top_k=3):
    if asymmetric:
        # E5 requires special prefixes.
        query_texts = [f"query: {q}" for q in queries]
        document_texts = [f"passage: {d}" for d in documents]
    else:
        # Symmetric/general model: same treatment on both sides.
        query_texts = queries
        document_texts = documents

    query_embeddings = model.encode(query_texts, normalize_embeddings=True)

    document_embeddings = model.encode(document_texts, normalize_embeddings=True)

    # Because embeddings are normalized, dot product = cosine similarity.
    scores = query_embeddings @ document_embeddings.T

    results = []

    for query_idx, query_scores in enumerate(scores):
        ranked = np.argsort(query_scores)[::-1][:top_k]

        results.append(
            {
                "query": queries[query_idx],
                "documents": [
                    {
                        "rank": rank + 1,
                        "index": int(doc_idx),
                        "score": float(query_scores[doc_idx]),
                        "text": documents[doc_idx],
                    }
                    for rank, doc_idx in enumerate(ranked)
                ],
            }
        )

    return results


def recall_at_k(results, relevant, k):
    correct = 0

    for query_idx, result in enumerate(results):
        retrieved = [item["index"] for item in result["documents"][:k]]

        if relevant[query_idx] in retrieved:
            correct += 1

    return correct / len(results)


def mrr_at_k(results, relevant, k):
    reciprocal_ranks = []

    for query_idx, result in enumerate(results):
        retrieved = [item["index"] for item in result["documents"][:k]]

        target = relevant[query_idx]

        if target in retrieved:
            rank = retrieved.index(target) + 1
            reciprocal_ranks.append(1 / rank)
        else:
            reciprocal_ranks.append(0)

    return sum(reciprocal_ranks) / len(reciprocal_ranks)


e5_results = retrieve(e5, queries, documents, asymmetric=True, top_k=3)

minilm_results = retrieve(minilm, queries, documents, asymmetric=False, top_k=3)


def print_results(name, results):
    print("\n" + "=" * 70)
    print(name)
    print("=" * 70)

    for i, result in enumerate(results):
        print(f"\nQuery: {result['query']}")

        for doc in result["documents"]:
            marker = " <-- RELEVANT" if doc["index"] == relevant[i] else ""

            print(f"{doc['rank']}. {doc['score']:.4f} | {doc['text']}{marker}")


print_results("E5 (Asymmetric Retrieval)", e5_results)
print_results("MiniLM (Symmetric)", minilm_results)

print("\n" + "=" * 70)
print("METRICS")
print("=" * 70)

print(f"E5     Recall@3: {recall_at_k(e5_results, relevant, 3):.3f}")

print(f"E5     MRR@3:    {mrr_at_k(e5_results, relevant, 3):.3f}")

print(f"MiniLM Recall@3: {recall_at_k(minilm_results, relevant, 3):.3f}")

print(f"MiniLM MRR@3:    {mrr_at_k(minilm_results, relevant, 3):.3f}")

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3329.09it/s]



E5 (Asymmetric Retrieval)

Query: What Python library is useful for manipulating datasets?
1. 0.8830 | Pandas is a Python library used for data manipulation and analysis. <-- RELEVANT
2. 0.8469 | Python is a programming language commonly used for data science and machine learning.
3. 0.8120 | SQL is a language used to query and manipulate relational databases.

Query: Which architecture is widely used for NLP?
1. 0.8551 | Transformers are neural network architectures widely used in natural language processing. <-- RELEVANT
2. 0.8088 | Python is a programming language commonly used for data science and machine learning.
3. 0.7751 | Pandas is a Python library used for data manipulation and analysis.

Query: What is the highest mountain in the world?
1. 0.8416 | Mount Everest is the highest mountain above sea level. <-- RELEVANT
2. 0.7494 | The Eiffel Tower is a famous landmark located in Paris, France.
3. 0.7436 | The Pacific Ocean is the largest ocean on Earth.

Query: Which ocean is t

## Task 7

In [3]:
with open("./corpus.txt", "r") as f:
    documents = f.read()

In [12]:
tokenizer = tiktoken.get_encoding("cl100k_base")
client = genai.Client()

In [17]:
per_token_price = 0.00000015

In [13]:
def chunk_text(text: str, chunk_size_tokens: int = 500, overlaps_token: int = 50):
    tokens = tokenizer.encode(text)
    chunks = []
    start = 0
    while start < len(tokens):
        end = min(start + chunk_size_tokens, len(tokens))
        chunks.append(tokenizer.decode(tokens[start:end]))
        start += chunk_size_tokens - overlaps_token
    return chunks

In [14]:
chunks = chunk_text(text=documents)

In [15]:
len(chunks)

44

In [ ]:
start = time.perf_counter()
embeddings = client.models.embed_content(model="gemini-embedding-001", contents=chunks)
latency = time.perf_counter() - start

In [21]:
latency

4.23757947499962

In [34]:
response = client.models.count_tokens(model="gemini-embedding-001", contents=chunks)

print(f"Total Tokens: {response.total_tokens}")

Total Tokens: 21951
